import type { NextPage } from 'next'
import Link from 'next/link';
import Head from 'next/head'
import Image from 'next/image'
import Container from '../components/Container';

const Home: NextPage = () => {
  return (
    <div className="bg-dark font-sans">
      <Head>
        <title>Matias Silva Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ms.jpg" />
      </Head>
      <>
        <Container />
      </>
    </div>
  )
}

export default Home
